### ISSUE TITLE
--tv-template and --movie-template examples

### ISSUE THREAD

**Issue by bshuler** [jpillora/media-sort#1]
In reading your documentation, I see that you have these values, but I am unsure how to utilize them.

/go/bin/media-sort --tv-template "./<title>/<title> S<season>E<episode>.<ext>" -w -r --tv-dir /data/tv --movie-dir /data/movie /data/completed

This gave me:

2016/07/31 05:08:51 [#20/24] /data/completed/MYSHOW - The Complete Season 7 [HDTV]/MYSHOW S07E20.mp4
  └─> File already exists '/data/tv/.--title---title- S-season-E-episode-.-ext-' (try setting --overwrite)

If you could give an example for how to create the template, that would be splendid.

Thanks!

**Comment by bshuler** [comment]
OK, I read your code and I found that this would work.. almost:

/go/bin/media-sort -d --tv-template '{{ .Name }}/{{ .Name }} S{{ printf "%02d" .Season }}E{{ printf "%02d" .Episode }}{{ if ne .ExtraEpisode -1 }}-{{ printf "%02d" .ExtraEpisode }}{{end}}.{{ .Ext }}'  -w -r --tv-dir /data/tv --movie-dir /data/movie /data/completed

I get from this:

2016/07/31 05:36:54 [#19/24] /data/completed/MYSHOW - The Complete Season 7 [HDTV]/MYSHOW.S07E19.HDTV.x264-LOL.mp4
  └─> /data/tv/MYSHOW-MYSHOW S07E19.mp4

Notice, I am attempting to get all of my shows into a directory whose name is the show name, but instead it is just adding show-show.

**Comment by wreckedred** [comment]
As an example:
Sort a directory of media into to two different directories one tv and one movies
media-sort -d -r --movie-dir /home/meuser/plex/movies --tv-dir /home/meuser/plex/tv /home/meuser/unsorted
