### ISSUE TITLE
option to use folder names instead of file names

### ISSUE THREAD

**Issue by nightmare-rg** [jpillora/media-sort#2]
hello,

i would prefer an option to switch to parent directory name for search and rename.

scene releases are named in a short version, so media-sort could not find the right information.

for example:

2016/11/24 14:52:20 [#29/52] Mr.Right.2015.German.720p.BluRay.x264-ENCOUNTERS/encounters-mrri_720p.mkv
  └─> No results (Google search failed)

filename: encounters-mrri_720p.mkv -> no chance to get the right information
parent dir name: Mr.Right.2015.German.720p.BluRay.x264-ENCOUNTERS -> all information are here

with correct file names it works like a charm:

2016/11/24 14:52:20 [#32/52] Pixels.2015.German.DTS.DL.720p.BluRay.x264-HQX/Pixels.2015.German.DTS.DL.720p.BluRay.x264-HQX.mkv
  └─> Pixels (2015).mkv

So i use at the moment a work arround via bash, but it is an ugly way to do this:
```
find . -type f -not -name test.sh | while read file
do
    dirname="$(dirname "$file")"
    new_name="${dirname##*/}"
    file_ext=${file##*.}
    if [ -n "$file_ext" -a  -n "$dirname" -a -n "$new_name" ]
    then
        echo "mv '$file' '$dirname/$new_name.$file_ext'"
    fi
done
```

**Comment by wreckedred** [comment]
Hey thanks

**Comment by rotsix** [comment]
Hey.
I'm facing the same issue, with some files named `Name.Season/Episode.ext`.

The cause is that `/sort/path_sort.go:runPathSort` send the file name only (e.g. `Episode.ext`) ([related code](https://github.com/jpillora/media-sort/blob/master/sort/path_sort.go#L82)).

Some simple solutions are: 
- sending full path from `<target>` as file name (with slashes replaced by dashes) (e.g. `<target>-Name.Season-Episode.ext`),
- sending both parent folder and file names (e.g. `Name.Season/Episode.ext`).

**Comment by rotsix** [comment]
Hi all,
The best solution would be to add an option specifying the number of folders to include.

```
  --num-folders, -n      number of folders to include in search (default 0)
```

Backward compatibility is guaranteed as `-n 0` is current behavior.

**Comment by jpillora** [comment]
Not a bad idea, so just concatenate last N folders and the filename, and
use that as the search query?

**Comment by rotsix** [comment]
Yep that should cover most use-cases.

**Comment by jpillora** [comment]
Release https://github.com/jpillora/media-sort/releases/tag/v2.5.2 in progress

**Comment by jpillora** [comment]
Added `  --num-dirs, -n            num ber of directories to include in search (default 0 where -1 means all dirs)`

**Comment by jpillora** [comment]
Released https://github.com/jpillora/media-sort/releases/tag/v2.6.2 test had windows path bug -_-
