### ISSUE TITLE
mediasort.invalidChars is too aggressive

### ISSUE THREAD

**Issue by rotsix** [jpillora/media-sort#24]
Hey there.

The regular expression in charge of invalid characters removal ([this one](https://github.com/jpillora/media-sort/blob/master/sort/strings.go#L22)) is a bit too aggressive for some characters such as accentuated ones, cedilla, amperstand, etc.

A dummy way around would be to include these characters in the `invalidChars` regexp.
A prettier solution is to use the [unicode character property](http://www.regular-expressions.info/unicode.html#prop) class which [seems to be included](https://github.com/google/re2/wiki/Syntax) in Go `regexp` module.

What do you think about it?

Edit: related class is `\p{L}`

**Comment by jpillora** [comment]
Yep, I think that's a reasonable change - what class(es) would you use?
maybe Letter and Punctuation?

**Comment by rotsix** [comment]
Considering [the go doc](https://github.com/google/re2/wiki/Syntax), it seems to be `\pN`, but [the unicode doc](http://www.regular-expressions.info/unicode.html#prop) says `\p{L}`.

**Comment by jpillora** [comment]
says you can use class names as well it seems "\p{Greek}" just thinking of
the ampersand case you mentioned

**Comment by rotsix** [comment]
According to the go doc, using `\p{Greek}` and `\p{L}` should be enough for most characters, whilst `&` may require to be explicited.
