### ISSUE TITLE
Example of Plex-compatible directory structure?

### ISSUE THREAD

**Issue by mauricesvay** [jpillora/media-sort#6]
Hello,

I'm not familiar with go templating syntax. Could you provide an example for generating a Plex-compatible directory structure?

I'm passing `"{{ .Name }}/{{ .Name }} S{{ printf \"%02d\" .Season }}E{{ printf \"%02d\" .Episode }}"` but slashes are converted to `-`.

**Comment by jpillora** [comment]
Unfortunately, templates were intended just for filenames, not paths. [This function](https://github.com/jpillora/media-sort/blob/5d63267bffe49d842c24340b70f9c22ecf03759c/sort/strings.go#L27) gets called on the result of the template, hence the dashes. This could be supported but would need a PR 👍

**Comment by mauricesvay** [comment]
Gotcha. Thanks for the answer!
